openapi: 3.0.3
info:
  title: Order Service API
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Development server

x-ogen:
  target: ./shared/pkg/openapi/order/v1
  package: orderv1

paths:
  /api/v1/orders:
    post:
      summary: Create new order
      operationId: createOrder
      tags:
        - Orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/create_order_request.yaml"
      responses:
        "201":
          description: Order successfully created
          content:
            application/json:
              schema:
                $ref: "./components/create_order_response.yaml"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "./components/errors/bad_request_error.yaml"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "./components/errors/internal_server_error.yaml"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "./components/errors/internal_server_error.yaml"

  /api/v1/orders/{order_uuid}:
    get:
      summary: Get order by UUID
      operationId: getOrder
      tags:
        - Orders
      parameters:
        - $ref: "./params/order_uuid.yaml"
      responses:
        "200":
          description: Order found
          content:
            application/json:
              schema:
                $ref: "./components/get_order_response.yaml"
        "404":
          description: Order not found
          content:
            application/json:
              schema:
                $ref: "./components/errors/not_found_error.yaml"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "./components/errors/internal_server_error.yaml"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "./components/errors/internal_server_error.yaml"

  /api/v1/orders/{order_uuid}/pay:
    post:
      summary: Pay order
      operationId: payOrder
      tags:
        - Orders
      parameters:
        - $ref: "./params/order_uuid.yaml"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/pay_order_request.yaml"
      responses:
        "200":
          description: Order successfully paid
          content:
            application/json:
              schema:
                $ref: "./components/pay_order_response.yaml"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "./components/errors/bad_request_error.yaml"
        "404":
          description: Order not found
          content:
            application/json:
              schema:
                $ref: "./components/errors/not_found_error.yaml"
        "409":
          description: Conflict (order already paid)
          content:
            application/json:
              schema:
                $ref: "./components/errors/conflict_error.yaml"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "./components/errors/internal_server_error.yaml"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "./components/errors/internal_server_error.yaml"

  /api/v1/orders/{order_uuid}/cancel:
    post:
      summary: Cancel order
      operationId: cancelOrder
      tags:
        - Orders
      parameters:
        - $ref: "./params/order_uuid.yaml"
      responses:
        "204":
          description: Order successfully cancelled
        "404":
          description: Order not found
          content:
            application/json:
              schema:
                $ref: "./components/errors/not_found_error.yaml"
        "409":
          description: Conflict (order already cancelled or paid)
          content:
            application/json:
              schema:
                $ref: "./components/errors/conflict_error.yaml"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "./components/errors/internal_server_error.yaml"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "./components/errors/internal_server_error.yaml"
