// Code generated by ogen, DO NOT EDIT.

package orderv1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelOrder implements cancelOrder operation.
//
// Cancel order.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) CancelOrder(ctx context.Context, params CancelOrderParams) (r CancelOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrder implements createOrder operation.
//
// Create new order.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateOrder(ctx context.Context, req *CreateOrderRequest) (r CreateOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrder implements getOrder operation.
//
// Get order by UUID.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) GetOrder(ctx context.Context, params GetOrderParams) (r GetOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PayOrder implements payOrder operation.
//
// Pay order.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (r PayOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *InternalServerErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *InternalServerErrorStatusCode) {
	r = new(InternalServerErrorStatusCode)
	return r
}
