version: '3.8'

services:
  payment:
    build:
      context: ../../../
      dockerfile: deploy/docker/payment/Dockerfile
    container_name: microservices-payment
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_FORMAT: ${LOG_FORMAT:-console}
      PAYMENT_GRPC_ADDRESS: ${PAYMENT_GRPC_ADDRESS:-:50053}
    ports:
      - "${PAYMENT_GRPC_PORT:-50053}:50053"
    networks:
      - microservices-network
    env_file:
      - ../../../payment/.env

networks:
  microservices-network:
    external: true